# Generated by Django 3.1.3 on 2020-12-05 07:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_category',
            field=models.CharField(choices=[('Banking and Finance', '1'), ('Food and Drinks', '2'), ('Groceries', '3'), ('Beauty parlour', '4'), ('Barber shop', '5'), ('Electronics', '6')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='business_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='hood_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
