# Generated by Django 3.1.3 on 2020-12-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20201205_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_category',
            field=models.CharField(choices=[('1', 'Banking and Finance'), ('2', 'Food and Drinks'), ('3', 'Groceries'), ('4', 'Beauty parlour'), ('5', 'Barber shop'), ('6', 'Electronics')], default='1', max_length=20),
        ),
    ]
