# Generated by Django 3.1.3 on 2020-12-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20201205_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
