# Generated by Django 3.1.3 on 2020-12-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='count',
            field=models.IntegerField(),
        ),
    ]
