# Generated by Django 3.1.3 on 2020-12-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idNo',
            field=models.IntegerField(default=0),
        ),
    ]
